if (self.CavalryLogger) { CavalryLogger.start_js(["15RK3"]); }

__d("CometGamingCoplayRejoinRoomModalContainerQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3545910805429051",metadata:{},name:"CometGamingCoplayRejoinRoomModalContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingLeftRailContainerQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3503654083064348",metadata:{},name:"CometGamingLeftRailContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingVideoRootContentQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3610047772424971",metadata:{},name:"CometGamingVideoRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingVideoRootHeroBannerQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3047231568713075",metadata:{},name:"CometGamingVideoRootHeroBannerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingVideoGameHubHeaderQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3603587519719138",metadata:{},name:"CometGamingVideoGameHubHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGamingVideoGameHubRootContentQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3956837637694106",metadata:{},name:"CometGamingVideoGameHubRootContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("buildCometGamingRoute.entrypoint",["CometGamingCoplayRejoinRoomModalContainerQuery$Parameters","CometGamingLeftRailContainerQuery$Parameters","JSResourceForInteraction","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f){"use strict";a=b("createContentAreaCompoundEntryPointBuilder")(b("JSResourceForInteraction")("CometGamingRoot.react").__setRef("buildCometGamingRoute.entrypoint"),function(a){return{coplayRejoinRoomModalQueryReference:{parameters:b("CometGamingCoplayRejoinRoomModalContainerQuery$Parameters"),variables:{}},leftRailQueryReference:{parameters:b("CometGamingLeftRailContainerQuery$Parameters"),variables:{}}}});e.exports=a}),null);
__d("CometGamingWebGamesFullPageCompatRoot.entrypoint",["JSResourceForInteraction","buildCometGamingRoute.entrypoint"],(function(a,b,c,d,e,f){"use strict";a=b("buildCometGamingRoute.entrypoint")(b("JSResourceForInteraction")("CometFullPageEntryPointCompatRoot.react").__setRef("CometGamingWebGamesFullPageCompatRoot.entrypoint"),function(a){a=a.routeProps.maintainKey;return{extraProps:{routeProps:{maintainKey:a}}}});e.exports=a}),null);
__d("CometGamingVideoRoot.entrypoint",["CometGamingVideoRootContentQuery$Parameters","CometGamingVideoRootHeroBannerQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGamingRoute.entrypoint","qex"],(function(a,b,c,d,e,f){"use strict";var g=b("WebPixelRatio").get();a=b("qex")._("1815432");var h=a!=null&&a===!0?b("qex")._("1815435"):null,i=a!=null&&a===!0?b("qex")._("1815436"):null,j=a!=null&&a===!0?b("qex")._("1815433"):null,k=a!=null&&a===!0?b("qex")._("1815434"):null;c=b("buildCometGamingRoute.entrypoint")(b("JSResourceForInteraction")("CometGamingVideoRoot.react").__setRef("CometGamingVideoRoot.entrypoint"),function(a){a=a.routeParams;return{queries:{contentQueryReference:{parameters:b("CometGamingVideoRootContentQuery$Parameters"),variables:{gv_game_card_height:i,gv_game_card_width:h,gv_video_thumbnail_image_height:k,gv_video_thumbnail_image_width:j,scale:g}},heroBannerQueryReference:{parameters:b("CometGamingVideoRootHeroBannerQuery$Parameters"),variables:{scale:g,videoID:a.video_id}}}}});e.exports=c}),null);
__d("CometGamingVideoGameHubRoot.entrypoint",["CometGamingVideoGameHubHeaderQuery$Parameters","CometGamingVideoGameHubRootContentQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometGamingRoute.entrypoint"],(function(a,b,c,d,e,f){"use strict";var g=b("WebPixelRatio").get();a=b("buildCometGamingRoute.entrypoint")(b("JSResourceForInteraction")("CometGamingVideoGameHubRoot.react").__setRef("CometGamingVideoGameHubRoot.entrypoint"),function(a){return{queries:{contentQueryReference:{parameters:b("CometGamingVideoGameHubRootContentQuery$Parameters"),variables:{game_id:a.routeProps.game_id,scale:g}},headerQueryReference:{parameters:b("CometGamingVideoGameHubHeaderQuery$Parameters"),variables:{params:{game_id:a.routeProps.game_id}}}}}});e.exports=a}),null);